[package]
name = "stoolie"
version = "0.1.0"
authors = ["Dj4t9n <pandeyjatin47@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path_abs = "0.5.1"
regex = "1.5.4"
sha2 = "0.9.5"
hex-literal = "0.3.1"